// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

import { connect } from 'react-redux';
import * as data from '../redux/actions';
import React, { useState, useEffect } from 'react'
import Router from 'next/router'

function button(props) {
  console.log("props===>", props)
  const [title, settitle] = useState("");

  useEffect(() => {
    console.log("navbar")
  }, [props.counter])

  const check = async () => {
    console.log("waiting")
    props.saveObj().then((e) => {
      console.log("object recieving", e)
      Router.push({
        pathname: '/page1',
      })
    }).catch((e) => {
      console.log(e.message)
    })
  }

  return (
    <>


      <h1>{props.counter}</h1>
      <button onClick={props.incrementCounter}>Increment</button>
      <button onClick={props.decrementCounter}>Decrement</button>
      <button onClick={props.resetCounter}>Reset</button>
      <button onClick={check}>My Function</button>


    </>
  )
}


const mapStateToProps = state => ({
  counter: state.datacount.value,
  authObj: state.datacount.obj
});






const mapDispatchToProps = {
  incrementCounter: data.incrementCounter,
  decrementCounter: data.decrementCounter,
  resetCounter: data.resetCounter,
  saveObj: data.saveObj
};






export default connect(mapStateToProps, mapDispatchToProps)(button);